---
title: "Indigenous DSI"
description: |
  A reading list to accompany the upcoming CBD webinar on the role of Indigenous Peoples and their Traditional Ecological Knowledge in the debate about Digital Sequence Information
site: distill::distill_website
---

## Indigenous Data Sovereignty

Wilkinson, M. D., Dumontier, M., Aalbersberg, Ij. J., Appleton, G., Axton, M., Baak, A., ... Mons, B. (2016). Comment: The FAIR Guiding Principles for scientific data management and stewardship. Scientific Data, 3, 1--9. <https://doi.org/10.1038/sdata.2016.18> [Lens link](https://www.lens.org/lens/scholar/article/070-462-022-251-464/main) Open Access

Rainie, S. C., Schultz, J. L., Briggs, E., Riggs, P., & Palmanteer-Holder, N. L. (2017). Data as a strategic resource: Self-determination, governance, and the data challenge for indigenous nations in the United States. International Indigenous Policy Journal, 8(2). <https://doi.org/10.18584/iipj.2017.8.2.1> [Lens link](https://www.lens.org/lens/scholar/article/088-106-961-734-82X/main) Open Access

The Global Indigenous Data Alliance (2019). The CARE Principles "CARE Principles for Indigenous Data Governance." The Global Indigenous Data Alliance. GIDA-global.org <https://www.gida-global.org/care> Open Access

Carroll, S. R., Garba, I., Figueroa-Rodríguez, O. L., Holbrook, J., Lovett, R., Materechera, S., ... Hudson, M. (2020). The CARE principles for indigenous data governance. Data Science Journal, 19(1), 1--12. <https://doi.org/10.5334/DSJ-2020-043> [Lens link](https://www.lens.org/lens/scholar/article/125-016-268-188-999/main) Open Access

Carroll, S. R., Herczog, E., Hudson, M., Russell, K., & Stall, S. (2021). Operationalizing the CARE and FAIR Principles for Indigenous data futures. *Scientific Data*, *8*(1), 8--13. <https://doi.org/10.1038/s41597-021-00892-0> <https://www.nature.com/articles/s41597-021-00892-0> Open Access

## Indigenous Peoples and Human Genomics

Arbour, L., & Cook, D. (2006). DNA on loan: Issues to consider when carrying out genetic research with aboriginal families and communities. Community Genetics, 9(3), 153--160. <https://doi.org/10.1159/000092651> [Lens link](https://www.lens.org/lens/scholar/article/077-868-122-028-539/main) Paywall

Tsosie, R. (2007). Cultural challenges to biotechnology: Native American genetic resources and the concept of cultural harm. Journal of Law, Medicine and Ethics, 35(3), 396--411. <https://doi.org/10.1111/j.1748-720X.2007.00163.x> [Lens link](https://www.lens.org/lens/scholar/article/059-749-266-027-071/main) Paywall

Reardon, J., & TallBear, K. (2012). "Your DNA is Our History", genomics, anthropology, and the construction of whiteness as property. Current Anthropology, 53(SUPPL. 5), 233--245. <https://doi.org/10.1086/662629> [Lens link](https://www.lens.org/lens/scholar/article/141-439-615-916-917/main) Open Access

Caron, N. R., Chongo, M., Hudson, M., Arbour, L., Wasserman, W. W., Robertson, S., ... Wilcox, P. (2020). Indigenous Genomic Databases: Pragmatic Considerations and Cultural Contexts. Frontiers in Public Health, 8(April), 1--7. <https://doi.org/10.3389/fpubh.2020.00111> [Lens link](https://www.lens.org/lens/scholar/article/047-389-039-058-60X/main) Open Access

Hudson, M., Garrison, N.A., Sterling, R. et al. Rights, interests and expectations: Indigenous perspectives on unrestricted access to genomic data. Nature Review Genetics 21, 377--384 (2020). <https://doi.org/10.1038/s41576-020-0228-x> [Lens link](https://www.lens.org/lens/scholar/article/095-099-808-413-027/main) Paywall

Powell, K. (2021). The broken promise that undermines human genome research. Nature, 590, 198--201. <https://doi.org/10.1038/d41586-021-00331-5> [Lens link](https://www.lens.org/lens/scholar/article/151-319-224-071-431/main) Open Access

Tsosie, K. S., Fox, K., & Yracheta, J. M. (2021). Genomics data: the broken promise is to Indigenous people. Nature, 591(7851), 529. <https://doi.org/10.1038/d41586-021-00758-w> [Lens link](https://www.lens.org/lens/scholar/article/048-022-574-660-833/main) Open Access

Tsosie, K. S., Yracheta, J. M., Kolopenuk, J. A., & Geary, J. (2021). We Have "Gifted" Enough: Indigenous Genomic Data Sovereignty in Precision Medicine. The American Journal of Bioethics, 21(4), 72--75. <https://doi.org/10.1080/15265161.2021.1891347> Open Access

## Ethnopharmacology

Rose, J., Quave, C. L., & Islam, G. (2012). The four-sided triangle of ethics in bioprospecting: Pharmaceutical business, international politics, socio-environmental responsibility and the importance of local stakeholders. Ethnobiology and Conservation, 1(2012), 1--25. <https://doi.org/10.15451/ec2012-8-1.3-1-25> [Lens link](https://www.lens.org/lens/scholar/article/020-496-348-760-084/main) Open Access

de la Parra, J., & Quave, C. L. (2017). Ethnophytotechnology: Harnessing the Power of Ethnobotany with Biotechnology. Trends in Biotechnology, 35(9), 802--806. <https://doi.org/10.1016/j.tibtech.2017.07.003> [Lens link](https://www.lens.org/lens/scholar/article/028-711-251-573-83X/main) Paywall

## DSI

Kupferschmidt, K. (2018). Biologists raise alarm over changes to biopiracy rules. Science, 361(6397), 14. <https://doi.org/10.1126/science.361.6397.14> [Lens link](https://www.lens.org/lens/scholar/article/184-479-861-565-91X/main) Paywall

Ambler, J., Diallo, A. A., Dearden, P. K., Wilcox, P., Hudson, M., & Tiffin, N. (2021). Including Digital Sequence Data in the Nagoya Protocol Can Promote Data Sharing. Trends in Biotechnology, 39(2), 116--125. <https://doi.org/10.1016/j.tibtech.2020.06.009> [Lens link](https://www.lens.org/lens/scholar/article/004-196-484-950-435/main) Paywall

## Guidelines and Principles

Institute of Aboriginal, A., & Strait Islander Studies, T. (1968). AIATSIS Code of Ethics for Aboriginal and Torres Strait Islander Research. Retrieved from [<http://aiatsis.gov.au/ethics>](http://aiatsis.gov.au/ethics){.uri}

Hudson, M., Beaton, A., Milne, M., Port, W., Russell, K., Smith, B., ... Wilcox, P. (2016). Te Mata Ira: Guidelines for Genomic Research with Māori. Retrieved from [<https://www.genomics-aotearoa.org.nz/sites/default/files/2019-03/Te-Mata-Ira-Genome-Research-Guidelines.pdf>](https://www.genomics-aotearoa.org.nz/sites/default/files/2019-03/Te-Mata-Ira-Genome-Research-Guidelines.pdf){.uri}

Tri-Council Policy Statement. (2018). Ethical conduct for research involving humans. In Holz als Roh- und Werkstoff: European Journal of Wood and Wood Industries (Vol. 45). [Lens link](https://www.lens.org/lens/scholar/article/082-148-585-538-178/main) <https://ethics.gc.ca/eng/policy-politique_tcps2-eptc2_2018.html> Open Access

## The CBD, the Nagoya Protocol and Access and Benefit Sharing

Wynberg, R., Schroeder, D., & Chennells, R. (2009). Indigenous Peoples, Consent and Benefit Sharing: Lessons from the San-Hoodia Case. Retrieved from [<https://link.springer.com/book/10.1007/978-90-481-3123-5>](https://link.springer.com/book/10.1007/978-90-481-3123-5){.uri} Paywall (Book)

Talaat, W. I. A. W. (2013). Protection of the Associated Traditional Knowledge on Genetic Resources: Beyond the Nagoya Protocol. Procedia - Social and Behavioral Sciences, 91, 673--678. <https://doi.org/10.1016/j.sbspro.2013.08.468> [Lens link](https://www.lens.org/lens/scholar/article/092-953-359-928-463/main) Open Access

Laird, S., International, P., & Wynberg, R. (2018). A Fact Finding and Scoping Study on Digital Sequence Information on Genetic Resources in the Context of the Convention on Biological Diversity and Nagoya Protocol (January). <https://www.cbd.int/doc/c/e95a/4ddd/4baea2ec772be28edcd10358/dsi-ahteg-2018-01-03-en.pdf> Open Access

Lawson, C., & Adhikari, K. (Eds.). (2018). Biodiversity, Genetic Resources and Intellectual Property: Developments in Access and Benefit Sharing (1st ed.). Routledge. <https://doi.org/10.4324/9781315098517> [Lens link](https://www.lens.org/lens/scholar/article/113-261-910-666-788/main) Paywall (Book)

Wynberg, R., & Laird, S. A. (2018). Fast Science and Sluggish Policy: The Herculean Task of Regulating Biodiscovery. Trends in Biotechnology, 36(1), 1--3. <https://doi.org/10.1016/j.tibtech.2017.09.002> [Lens link](https://www.lens.org/lens/scholar/article/070-462-022-251-464/main) Open Access

Watanabe, M. E. (2019). The Nagoya protocol: The conundrum of defining digital sequence information. BioScience, 69(6), 480. <https://doi.org/10.1093/biosci/biz034> [Lens link](https://www.lens.org/lens/scholar/article/022-476-015-755-37X/main) Open Access

Karger, E. J., & Scholz, A. H. (2021). DSI, the Nagoya Protocol, and Stakeholders' Concerns. Trends in Biotechnology, 39(2), 110--112. <https://doi.org/10.1016/j.tibtech.2020.09.008> [Lens link](https://www.lens.org/lens/scholar/article/136-113-291-195-672/main) Paywall

## Novel Approaches to Indigenous Knowledge and Genomics

Robinson, D., & Raven, M. (2017). Identifying and Preventing Biopiracy in Australia: patent landscapes and legal geographies for plants with Indigenous Australian uses. Australian Geographer, 48(3), 311--331. <https://doi.org/10.1080/00049182.2016.1229240> [Lens link](https://www.lens.org/lens/scholar/article/137-968-300-004-04X/main) Paywall

Collier-Robinson, L., Rayne, A., Rupene, M., Thoms, C., & Steeves, T. (2019). Embedding indigenous principles in genomic research of culturally significant species: A conservation genomics case study. New Zealand Journal of Ecology, 43(3). <https://doi.org/10.20417/nzjecol.43.36> [Lens link](https://www.lens.org/lens/scholar/article/045-961-968-677-933/main) Open Access

Inwood, S. N., McLaughlin, G. M., Buckley, T. R., Cox, M. P., Handley, K. M., Steeves, T. E., ... Dearden, P. K. (2020). Opportunities for modern genetic technologies to maintain and enhance aotearoa New Zealand's bioheritage. New Zealand Journal of Ecology, 44(2), 1--13. <https://doi.org/10.20417/nzjecol.44.22> [Lens link](https://www.lens.org/lens/scholar/article/024-701-441-809-01X/main) Open Access

Anderson, J., & Hudson, M. (2020). The Biocultural Labels Initiative: Supporting Indigenous rights in data derived from genetic resources. Biodiversity Information Science and Standards, 4. <https://doi.org/10.3897/biss.4.59230> [Lens link](https://www.lens.org/lens/scholar/article/044-786-718-614-233/main) Open Access

Robinson, D. F., & Raven, M. (2020). Recognising Indigenous customary law of totemic plant species: Challenges and pathways. Geographical Journal, 186(1), 31--44. <https://doi.org/10.1111/geoj.12320> [Lens link](https://www.lens.org/lens/scholar/article/046-544-266-448-465/main) Open Access

Sherman, B., Henry, R., (2021) Access to biodiversity for food production: Reconciling open access digital sequence information with access and benefit sharing, Molecular Plant, <https://doi.org/10.1016/j.molp.2021.03.005> [Lens link](https://www.lens.org/lens/scholar/article/037-891-879-282-162/main) Paywall


**If you would like to suggest additional reading materials please contact jasmine@oneworldanalytics.com**
